config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "/now_showing" => "cinefile#now_showing"

  resources :users do
    resources :cinefile do
      resources :list_films
    end
  end

  resources :films do
    resources :screenings, :only => [:show_screenings_for_film] do
      collection do
        get :show_screenings_for_film
      end
    end
  end

  resources :cinemas do
    resources :screenings, :only => [:index, :new, :create, :show, :destroy]
  end

  get "/search" => "search#new_search"

  root to: "static_pages#home"

end

app/models/cinefile.rb
class Cinefile < ActiveRecord::Base
  belongs_to :user
  has_many :list_films
  has_many :films, through: :list_film
end

app/controllers/cinefile_controller.rb
class CinefileController < ApplicationController

  def create
    @user = current_user
      if @user.cinefile.nil?
       @cinefile = Cinefile.create
       @user.cinefile = @cinefile
      end
    redirect_to user_cinefile_path(@user.id, @user.cinefile.id)
  end

  def show
    @cinemas = Cinema.all
    @screenings = Screening.all
    @films = Film.all
    @user = current_user
    @cinefile = @user.cinefile
    @list_films = @cinefile.list_films.all
    @list_count = @list_films.count
    @films_with_upcoming_screenings = []
    @other_films_in_cinefile = []
    @list_films.each do |list_film|
      @films.each do |film|
        if film.id == list_film.film_id
          if film.upcoming_screening?
            days = film.days_until_nearest_screening
            film_hash = {film: film, days: days}
            @films_with_upcoming_screenings << film_hash
          else
            @other_films_in_cinefile << film
          end
        end
      end
    end
    @films_with_upcoming_screenings.sort_by! { |hsh| hsh[:days] }
    @films_with_upcoming_screenings.map! { |film| film[:film] }

    @film = Film.new
    if params[:film].nil?
      @searched_film = nil
    else
      @searched_film = params[:film]
    end
  end

  def now_showing
    @user = current_user
      if @user.cinefile.nil?
       @cinefile = Cinefile.create
       @user.cinefile = @cinefile
      end
    redirect_to user_cinefile_list_films_path(@user.id, @user.cinefile.id)
  end
end

app/helpers/cinefile_helper.rb
module CinefileHelper
end

app/views/cinefile/show.html.erb
<center>
  <h1><%= "#{@user.username}'s Cinefile" %></h1>
  <!-- <br /> -->
  <% if @list_count == 0 %>
    Your Cinefile is empty :(<br />
    Add films and the Cinefile team will keep you informed of upcoming screenings.
  <% else %>
    Cinefiled: <span class="totals"><%= @list_count %></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Upcoming: <span class="totals"><%= @films_with_upcoming_screenings.count %></span><br /><br />
  <% end %>
  <%= form_tag("/search", method: "get", :class => "form") do %>
    <%= label_tag(:search, "", :id => "label") %>
    <%= text_field_tag(:search, "", :id => "film") %>
    <%= submit_tag("Search", :class => "submit") %>
  <% end %>
  <br />
  <% if !@searched_film.nil? %>
    <%= form_for @film, :html => { :class => "form" } do |f| %>
      <% @search = Tmdb::Search.new %>
      <% @search.resource('movie') %>
      <% @search.query(@searched_film) %>
      <% @results = @search.fetch %>
      <% @select_list = @results.collect {|movie| [ movie['title'] + " " + movie['release_date'][0..3],
         movie['title'] + "," + movie['release_date'][0..3] + "," + movie['id'].to_s + "," + movie["backdrop_path"].to_s ] } %>
      <%= label_tag("") %>
      <%= select_tag "film_record", options_for_select(@select_list), { :class => "submitag" } %>
      <%= f.submit "Add", :html => { :class => "submit"}  %>
    <% end %>
  <% end %>
  <br /><br />
</center>

<div class="container">
  <% @films_with_upcoming_screenings.each do |film| %>
    <div class="row">
      <div class="col-md-3", align="right">
        <br /><br /><br /><br /><br /><br /><br /><br />
        <%= image_tag("Upcoming_Screening.png", :class => 'upcoming') %>
      </div>
      <div class="col-md-6">
        <center>
          <h2 class="title"><%= film.title.upcase %> (<%= film.release_year %>)</h2>
          <br />
          <%= image_tag("http://cf2.imgobject.com/t/p/w500/" + film.poster_path, :class => 'img-rounded') %>
          <% @list_films.each do |list_film| %>
            <% if list_film.film_id == film.id %>
              <% @list_film = list_film %>
            <% end %>
          <% end %>
          <br /><br />
          <div class="remove">
            <%= link_to "", user_cinefile_list_film_path(@user, @cinefile, @list_film ), method: :delete, :class => 'glyphicon glyphicon-trash' %>
          </div>
          <br />

        </center>
      </div>
      <div class="col-md-3", style="text-align: left;">
        <br /><br /><br /><br /><br /><br /><br /><br />
          <% if film.days_until_nearest_screening == 0 %>
            <%= image_tag("today.png", :class => 'days_until_screening') %>
          <% elsif film.days_until_nearest_screening == 1 %>
            <%= image_tag("tomorrow.png", :class => 'days_until_screening') %>
          <% else %>
            <%= image_tag("#{film.days_until_nearest_screening}_days.png", :class => 'days_until_screening') %>
          <% end %>
          <br>
          <%= link_to "Show me where!", show_screenings_for_film_film_screenings_path(film), class: "btn btn-default" %>
      </div>
    </div>
    <br /><br /><br />
  <% end %>

  <% @other_films_in_cinefile.each do |film| %>
    <div class="row">
      <div class="col-md-3", align="right">
        <br /><br /><br /><br /><br /><br /><br /><br />
      </div>
      <div class="col-md-6">
        <center>
          <h2 class="title"><%= film.title.upcase %> (<%= film.release_year %>)</h2>
          <br />
          <%= image_tag("http://cf2.imgobject.com/t/p/w500/" + film.poster_path, :class => 'img-rounded') %>
          <% @list_films.each do |list_film| %>
            <% if list_film.film_id == film.id %>
              <% @list_film = list_film %>
            <% end %>
          <% end %>
          <br /><br />
          <div class="remove">
            <%= link_to "", user_cinefile_list_film_path(@user, @cinefile, @list_film ), method: :delete, :class => 'glyphicon glyphicon-trash' %>
          </div>
        </center>
      </div>
      <div class="col-md-3", style="text-align: left;">
        <br /><br /><br /><br /><br /><br /><br /><br />
      </div>
    </div>
    <br /><br /><br /><br />
  <% end %>
</div>