config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "/now_showing" => "cinefile#now_showing"

  resources :users do
    resources :cinefile do
      resources :list_films
    end
  end

  resources :films do
    resources :screenings, :only => [:show_screenings_for_film] do
      collection do
        get :show_screenings_for_film
      end
    end
  end

  resources :cinemas do
    resources :screenings, :only => [:index, :new, :create, :show, :destroy]
  end

  get "/search" => "search#new_search"

  root to: "static_pages#home"

end

app/models/cinema.rb
class Cinema < ActiveRecord::Base
  has_many :screenings, dependent: :destroy
  has_many :films, through: :screenings
end

app/controllers/cinemas_controller.rb
class CinemasController < ApplicationController

  def index
    @cinemas =Cinema.all
  end

  def new
    @cinema = Cinema.new
  end

  def create
    @cinema = Cinema.create(cinema_params)
    redirect_to cinemas_path
  end

  def show
    @cinema = Cinema.find(params[:id])
  end

  def edit
    @cinema = Cinema.find(params[:id])
  end

  def update
    @cinema = Cinema.find(params[:id])
    @cinema.update(cinema_params)
    redirect_to cinemas_path
  end

  def destroy
    @cinema = Cinema.find(params[:id])
    @cinema.destroy
    flash[:notice] = 'Cinema deleted successfully'
    redirect_to cinemas_path
  end

private

  def cinema_params
    params.require(:cinema).permit(:name, :address, :postcode, :phone, :website)
  end
end

app/helpers/cinemas_helper.rb
module CinemasHelper
end

app/views/cinemas/edit.html.erb
<%= form_for @cinema do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %>
  <%= f.label :address, "Address" %>
  <%= f.text_field :address %>
  <%= f.label :postcode, "Postcode" %>
  <%= f.text_field :postcode %>
  <%= f.label :phone, "Phone" %>
  <%= f.text_field :phone %>
  <%= f.label :website, "Website" %>
  <%= f.url_field :website %>
  <%= f.submit "Update Cinema" %>
<% end %>

app/views/cinemas/index.html.erb
<%= link_to "Add Cinema", new_cinema_path %> <br>
<% if @cinemas.any? %>
  <% @cinemas.each do |cinema| %><br>
    <%= link_to cinema.name, cinema_path(cinema) %><br>
    <%= cinema.address%>, <%= cinema.postcode %><br>
    Phone: <%= cinema.phone %><br>
    Website: <%= cinema.website %><br>
    Screenings: <% cinema.screenings.all.each do |screening| %>
    <%= screening.film_id %>
   <% end %><br>
  <% end %>
<% end %>

app/views/cinemas/new.html.erb
<%= form_for @cinema do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %>
  <%= f.label :address, "Address" %>
  <%= f.text_field :address %>
  <%= f.label :postcode, "Postcode" %>
  <%= f.text_field :postcode %>
  <%= f.label :phone, "Phone" %>
  <%= f.text_field :phone %>
  <%= f.label :website, "Website" %>
  <%= f.url_field :website %>
  <%= f.submit "Add Cinema" %>
<% end %>

app/views/cinemas/show.html.erb
<%= @cinema.name %><br>
<%= @cinema.address %>, <%= @cinema.postcode %><br>
Phone: <%= @cinema.phone %><br>
Website: <%= @cinema.website %><br>
<%= link_to "Edit", edit_cinema_path(@cinema) %><br>
<%= link_to "Delete", cinema_path(@cinema), method: :delete %>
<br>
<br>
Screenings: <% @cinema.screenings.all.each do |screening| %><br>
Film_id: <%= screening.film_id %><br>
Screen_date: <%= screening.screen_date %><br>
Screen_time: <%= screening.screen_time %><br>
<%= link_to "Delete screening #{screening.id}", cinema_screening_path(@cinema, screening), method: :delete %>
<% end %>
<br>
<br>
<%= link_to "Add screening to #{@cinema.name}", new_cinema_screening_path(@cinema) %>
 <br>