config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "/now_showing" => "cinefile#now_showing"

  resources :users do
    resources :cinefile do
      resources :list_films
    end
  end

  resources :films do
    resources :screenings, :only => [:show_screenings_for_film] do
      collection do
        get :show_screenings_for_film
      end
    end
  end

  resources :cinemas do
    resources :screenings, :only => [:index, :new, :create, :show, :destroy]
  end

  get "/search" => "search#new_search"

  root to: "static_pages#home"

end

app/models/cinefile.rb
class Cinefile < ActiveRecord::Base
  belongs_to :user
  has_many :list_films
  has_many :films, through: :list_film
end

app/models/cinema.rb
class Cinema < ActiveRecord::Base
  has_many :screenings, dependent: :destroy
  has_many :films, through: :screenings
end

app/models/film.rb
class Film < ActiveRecord::Base
  has_many :cinefiles, through: :list_film
  has_many :list_films
  has_many :screenings
  has_many :cinemas, through: :screenings

  validates :tmdb_id, uniqueness: true

  def upcoming_screening?
    return true if days_until_nearest_screening && screenings_within_the_fortnight?
    return false
  end

  def days_until_nearest_screening
    @array_of_days_until_screenings = screenings.all.map { |screening| screening.screen_date.day - Time.now.day }
    @array_of_days_until_screenings.select! { |day| day >= 0 }
    @array_of_days_until_screenings.min
  end

private

  def screenings_within_the_fortnight?
    days_until_nearest_screening.between?(0, 14)
  end
end

app/models/list_film.rb
class ListFilm < ActiveRecord::Base
  belongs_to :cinefile
  belongs_to :film
end

app/models/screening.rb
class Screening < ActiveRecord::Base
  belongs_to :film
  belongs_to :cinema
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessor :login

  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]

  has_one :cinefile

  validates :username, :presence => true, :uniqueness => { :case_sensitive => false}

  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase}]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_hash).first
    end
  end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController

  def new
    @film = Film.new
  end

  def index
    @films = Film.all
  end

  def create
    @user = current_user
    @cinefile = @user.cinefile
    cinefile_id = @cinefile.id
    @film_info = params["film_record"].split(",")
    @film_release_year = @film_info.delete(@film_info[-3])
    @tmdb_id = @film_info.delete(@film_info[-2])
    @poster_path = @film_info.delete(@film_info[-1])
    @title = @film_info.join(',')
    film_not_in_database = Film.find_by(tmdb_id: @tmdb_id).nil?
    if film_not_in_database
      Film.create(title: @title, tmdb_id: @tmdb_id, release_year: @film_release_year, poster_path: @poster_path)
    end
    film_id = Film.find_by(tmdb_id: @tmdb_id).id
    list_film_not_in_cinefile = ListFilm.find_by(film_id: film_id, cinefile_id: cinefile_id).nil?
    if list_film_not_in_cinefile
      ListFilm.create(film_id: film_id, cinefile_id: cinefile_id)
      flash[:notice] = "#{@title} has successfully been Cinefiled!"
    else
      flash[:alert] = "#{@title} has previously been Cinefiled"
    end
    redirect_to user_cinefile_path(@user.id, @cinefile.id)
  end

  def destroy
    @film = Film.find(params[:id])
    @film.destroy
    flash[:notice] = 'Film deleted successfully'
    redirect_to films_path
  end

private

  def film_params
    params.require(:film).permit(:title)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  require "pry"

  def new_search
    @user = current_user
    @cinefile = @user.cinefile
    if params[:search] == ""
      flash[:alert] = "Please enter a film in the search box"
      redirect_to user_cinefile_path(@user, @cinefile)
    else
      @searched_film = params[:search]
      redirect_to user_cinefile_path(@user, @cinefile, :film => @searched_film)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cinefile_helper.rb
module CinefileHelper
end

app/helpers/cinemas_helper.rb
module CinemasHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/list_film_helper.rb
module ListFilmHelper
end

app/helpers/list_films_helper.rb
module ListFilmsHelper
end

app/helpers/screenings_helper.rb
module ScreeningsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a href="/" class="pull-left"><%= image_tag("Blue_Logo2.png", :class => "logo") %></a>
      <!-- <a class="navbar-brand" href="/"><%= image_tag("Blue_Logo.png", :class => "logo") %></a> -->
    </div>
      <ul class='nav navbar-nav navbar-right'>
        <% if user_signed_in? %>
        <li><%= link_to "NOW SHOWING", now_showing_path
       %></li>
        <li><%= link_to "CINEFILE", user_cinefile_index_path(current_user), method: :post %></li>
          <li><%= link_to "LOG OUT", destroy_user_session_path, method: :delete %></li>
          <% else %>
          <li><%= link_to "LOG IN", new_user_session_path %></li>
          <li><%= link_to "SIGN UP", new_user_registration_path %></li>
        <% end %>
      </ul>
  </div>
</nav>

app/views/layouts/_messages.html.erb
<% if notice || alert %>
  <div id="message" class="flash-message <%= notice ? "notice" : ""%><%= alert ? "error" : ""%>">
    <div class="container container_12 clearfix">
      <div class="grid_12">
        <% if notice %>
          <p><%= notice %></p>
        <% elsif alert %>
          <p><%= alert %></p>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Cinefile</title>
  <link href="css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Baloo+Paaji" rel="stylesheet">
</head>
<body>
  <br /><br /><p></p>

  <%= render "layouts/messages" %>
  <%= render "layouts/header" %>

<%= yield %>

</body>
</html>